### ISSUE TITLE
Automate distribution dependency bumps

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1164]
The distribution has several [dependencies](https://github.com/asciidoctor/asciidoctorj/blob/main/asciidoctorj-distribution/build.gradle) that depend on manual updates.
To avoid having to keep track manually we could start automating them with dependabot on weekly basis.

I am considering restricting it for now to:
* org.asciidoctor:asciidoctorj-epub3
* org.asciidoctor:asciidoctorj-diagram
* org.asciidoctor:asciidoctorj-diagram-ditaamini
* org.asciidoctor:asciidoctorj-diagram-plantuml
* org.asciidoctor:asciidoctorj-pdf
* org.asciidoctor:asciidoctorj-revealjs
* As well as jruby and jruby-complete for all modules.

If we consider this works for us, we can extend it to other dependencies to reduce manual work.

**Comment by abelsromero** [comment]
After checking 

I think we could narrow branch v2.5.x with

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v2.5.x)"
    target-branch: "v2.5.x"
    allow:
      - dependency-name: "org.asciidoctor:asciidoctorj-pdf"
      - dependency-name: "org.asciidoctor:asciidoctorj-epub3"
      - dependency-name: "org.asciidoctor:asciidoctorj-diagram-ditaamini"
      - dependency-name: "org.asciidoctor:asciidoctorj-diagram-plantuml"
      - dependency-name: "org.asciidoctor:asciidoctorj-revealjs"
```

This needs to be on the main branch though...that's how dependabot does it's things
